# Generated by Django 3.1.6 on 2021-02-22 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('am', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruth_weather.am')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruth_weather.pm')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('rain_chance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('time', models.TimeField(default='08:00')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruth_weather.report')),
            ],
        ),
        migrations.AddField(
            model_name='pm',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruth_weather.weather'),
        ),
        migrations.AddField(
            model_name='am',
            name='weather',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruth_weather.weather'),
        ),
    ]
