# Generated by Django 3.1.6 on 2021-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruth_weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='am',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='pm',
            name='weather',
        ),
        migrations.AddField(
            model_name='am',
            name='prec',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='am',
            name='temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pm',
            name='prec',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pm',
            name='temp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='eve_temp',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
