# Generated by Django 3.1.6 on 2021-02-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruth_weather', '0003_auto_20210224_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='oulook',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
