# Generated by Django 3.1.6 on 2021-02-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruth_weather', '0004_report_oulook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='oulook',
            new_name='outlook',
        ),
    ]
